### PR TITLE
Test case for lint PSI checks not running with Buck

### PR DESCRIPTION
**Pull request by felipecsl**
This PR is a test case for demonstrating that Buck doesn't seem to correctly run PSI based lint checks.

How to verify:

```
./gradlew libraries:lintErrorLibrary:lint # 1 error found
./buckw build //libraries/lintErrorLibrary:lint_release # no errors found
```

### CODE REVIEW

**Comment by kageiit** [comment]
With the test case, even `./gradlew libraries:lintErrorLibrary:lint` is not exiting with any errors. Can you make sure the check actually fails in gradle so we can compare with the buck linter?

**Comment by kageiit** [comment]
btw you do not need to make any changes whatsoever to `libraries/customLintLibrary/build.gradle` and `libraries/lintErrorLibrary/build.gradle` from master.

**Comment by clonetwin26** [comment]
Maybe we have to bump the build tools version to get latest lint?
https://github.com/uber/okbuck/blob/master/dependencies.gradle#L20

**Comment by felipecsl** [comment]
hmm looks like `compile project (':libraries:customLintLibrary')` is not enough to have gradle pick up the custom lint check. If I use the install task then it works fine.

**Comment by felipecsl** [comment]
Seems like `lintChecks` instead of `compile` works

**Comment by kageiit** [comment]
@felipecsl Can you please try to rebase this PR on master? UAST/Psi lints should be picking up things correctly now

**Comment by kageiit** [comment]
Assuming this works correctly and closing due to inactivity. Feel free to comment if there is an issue and we can definitely followup

**Pull request closed without merging**
