### PR TITLE
Add missing API versions for Roboelectric

### PR DESCRIPTION
**Pull request by vicmns**
Adding missing APIS 32 and 33 so they can be resolved by the OkBuck build system

**Description**:
Adding missing APIs levels to Roboelectric manager.

### CODE REVIEW

**Comment by tyvsmith** [comment]
Please update [TestExtension.java](https://github.com/uber/okbuck/blob/7faa0c9313a2011b23bf15482b4af56c29d8bb91/buildSrc/src/main/java/com/uber/okbuck/extension/TestExtension.java#L21) to the latest preinstrumented verison while we're at it (same PR or separate).

Also, it would be good to add a CustomAPI support so we can update this without a PR, but we don't need to block on making that happen now.

**Comment by tyvsmith** [comment]
Is this stalled?

**Comment by vicmns** [comment]
Kind off, I'm still not able to get CI to resolve this artifact....
```
FAILURE com.uber.okbuck.example.empty.EmptyLibraryUnitTest addition_isCorrect: Path is not a file: /home/runner/work/okbuck/okbuck/buck-out/gen/.okbuck/workspace/robolectric/robolectric_cache/android-all-instrumented-8.1.0-robolectric-4611349-i3.jar
```

**Comment by gpolak** [comment]
We should abandon this PR as it's superseded by https://github.com/uber/okbuck/pull/983

**Pull request closed without merging**
