### PR TITLE
Bump Android Gradle Plugin to 3.4.0

### PR DESCRIPTION
**Pull request by NickFirmani**
**Description**:
AGP 3.4 brings quite a few new features, and is required for one of my projects, so here is a PR to bump it.

### CODE REVIEW

**Comment by kageiit** [comment]
3.4 causes dependency conflicts in our projects so we cannot bump this immediately. Please cut an internal version while we investigate

**Comment by kageiit** [comment]
Cc @raviagarwal7

**Comment by kageiit** [comment]
Please use #840 to track progress on this

**Comment by NickFirmani** [comment]
Sure, I have an internal version of it, with this patch applied. I figured you'd just merge this when you're ready to update internally to 3.4

**Comment by rifqimfahmi** [comment]
How do you make an internal version of it?

**Comment by raviagarwal7** [comment]
> How do you make an internal version of it?

- can change the version in `buildSrc/build.gradle` 
- run `./gradlew publishToMavenLocal --stacktrace`
- upload to internal artifactory which can be found in`~/.m2/repository/`

**Comment by rifqimfahmi** [comment]
Could you elaborate more on the steps? I am sorry to ask this because I am not familiar with how the nitty-gritty of Android build tool entirely works :/. Maybe if you have some sources to how to get started and the feel to share that would be awesome 😀

**Pull request closed without merging**
